

USE master
GO

CREATE DATABASE TaskR
GO

USE TaskR
GO
	CREATE TABLE AppRole
(
	Id INT PRIMARY KEY IDENTITY,
	RoleName VARCHAR(20) NOT NULL UNIQUE
)
GO
INSERT INTO AppRole VALUES
	('FreeUser'),
	('Admin'),
	('PremiumUser')
GO
CREATE TABLE AppUser
(
	Id INT PRIMARY KEY IDENTITY,
	Username VARCHAR(50) NOT NULL,
	PasswordHash BINARY(32) NOT NULL,
	Salt BINARY(32) NOT NULL,
	RegisteredOn DATETIME NOT NULL,
	AppRoleId INT NOT NULL DEFAULT(0) REFERENCES AppRole(Id)
)
GO
CREATE TABLE ToDoList
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(30) NOT NULL
)

CREATE TABLE Task
(
	Id INT PRIMARY KEY IDENTITY,
	[Descripton] VARCHAR(100) NOT NULL,
	ToDoListId INT NOT NULL FOREIGN KEY REFERENCES ToDoList,
	IsCompleted BIT NOT NULL,
	CreatedOn DATETIME NOT NULL,
	CompletedOn DATETIME NOT NULL,
	PricePerPerson DECIMAL(9,2) NULL,
	Deadline DATETIME NOT NULL, 
	Priority INT 
)
CREATE TABLE Tags
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(10) NOT NULL,
	HexColor CHAR(6) NOT NULL
)

CREATE TABLE TaskTags
(
	TaskId INT NOT NULL FOREIGN KEY REFERENCES Task,
	TagsId INT NOT NULL FOREIGN KEY REFERENCES Tags,
	  PRIMARY KEY (TaskId,TagsId)
)

